version: "3.7"

services:
  redis:
    container_name: 2FA_level2_redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  database:
    container_name: 2FA_level2_database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    image: otp/db
    build: ./db
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password

  proxy:
    container_name: 2FA_level2_proxy
    ports:
      - "4202:80"
    image: nginx:stable
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  web:
    container_name: 2FA_level2_web
    depends_on:
      - database
    build: ./web
    environment:
      - MYSQL_HOSTNAME=database
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    volumes:
      - ./web/src:/var/www/html/
