version: "3.6"
services:
  web:
    container_name: level2_web
    build: ./web
    ports:
      - 8092:80
    environment:
      # These password and stuff is not neccesarry too secret
      - MYSQL_ROOT_PASSWORD=efddc501e4c9aaa7e63854b9ff864a75
      - MYSQL_HOSTNAME=db
      - MYSQL_DATABASE=blog
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=password
    volumes:
      - ./web/html:/var/www/html
    restart: unless-stopped
  db:
    container_name: level2_db
    build: ./database
    expose:
      - 3306
    environment:
      # These password and stuff is not neccesarry too secret
      - MYSQL_ROOT_PASSWORD=efddc501e4c9aaa7e63854b9ff864a75
      - MYSQL_DATABASE=blog
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped