version: "3.0"

services:
  database:
    container_name: 2FA_level3_database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    image: otp/db
    build: ./db
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password

  proxy:
    container_name: 2FA_level3_proxy
    ports:
      - "4203:80"
    image: nginx:stable
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  web:
    container_name: 2FA_level3_web
    depends_on:
      - database
    ports:
      - "4204:80"
    build: ./web
    environment:
      - MYSQL_HOSTNAME=database
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
